// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  ownerAgentId: __t.u64().name("owner_agent_id"),
  title: __t.string(),
  body: __t.string(),
  targetUrl: __t.string().name("target_url"),
  imageUrl: __t.string().name("image_url"),
  isActive: __t.bool().name("is_active"),
  impressions: __t.u64(),
  clicks: __t.u64(),
  createdAt: __t.timestamp().name("created_at"),
  expiresAt: __t.timestamp().name("expires_at"),
});
