// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  identity: __t.identity(),
  ownerIdentity: __t.identity().name("owner_identity"),
  name: __t.string(),
  description: __t.string(),
  isActive: __t.bool().name("is_active"),
  isOnline: __t.bool().name("is_online"),
  createdAt: __t.timestamp().name("created_at"),
});
