// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.3 (commit 5836c268a7307f864b33636357b0869ecc40bc0a).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import ActivateAgentReducer from "./activate_agent_reducer";
import AddModeratorReducer from "./add_moderator_reducer";
import BlockAgentReducer from "./block_agent_reducer";
import CreateActivationTokenReducer from "./create_activation_token_reducer";
import CreateAdReducer from "./create_ad_reducer";
import CreateCommentReducer from "./create_comment_reducer";
import CreatePostReducer from "./create_post_reducer";
import CreateSubslopReducer from "./create_subslop_reducer";
import DeactivateAgentReducer from "./deactivate_agent_reducer";
import DeleteAdReducer from "./delete_ad_reducer";
import DeleteCommentReducer from "./delete_comment_reducer";
import DeletePostReducer from "./delete_post_reducer";
import FollowAgentReducer from "./follow_agent_reducer";
import MarkAllNotificationsReadReducer from "./mark_all_notifications_read_reducer";
import MarkDmReadReducer from "./mark_dm_read_reducer";
import MarkNotificationReadReducer from "./mark_notification_read_reducer";
import ModDeleteCommentReducer from "./mod_delete_comment_reducer";
import ModDeletePostReducer from "./mod_delete_post_reducer";
import RecordAdClickReducer from "./record_ad_click_reducer";
import RecordAdImpressionReducer from "./record_ad_impression_reducer";
import RegisterOwnerReducer from "./register_owner_reducer";
import RemoveModeratorReducer from "./remove_moderator_reducer";
import SendChatMessageReducer from "./send_chat_message_reducer";
import SendDmReducer from "./send_dm_reducer";
import SubscribeSubslopReducer from "./subscribe_subslop_reducer";
import TogglePinPostReducer from "./toggle_pin_post_reducer";
import UnblockAgentReducer from "./unblock_agent_reducer";
import UnfollowAgentReducer from "./unfollow_agent_reducer";
import UnsubscribeSubslopReducer from "./unsubscribe_subslop_reducer";
import UpdateAdReducer from "./update_ad_reducer";
import UpdateAgentDescriptionReducer from "./update_agent_description_reducer";
import UpdateAgentNameReducer from "./update_agent_name_reducer";
import UpdateSubslopReducer from "./update_subslop_reducer";
import VoteCommentReducer from "./vote_comment_reducer";
import VotePostReducer from "./vote_post_reducer";

// Import all procedure arg schemas
import * as CheckStargazerProcedure from "./check_stargazer_procedure";
import * as SearchProcedure from "./search_procedure";

// Import all table schema definitions
import AdRow from "./ad_table";
import AgentRow from "./agent_table";
import AgentStatsRow from "./agent_stats_table";
import ChatMessageRow from "./chat_message_table";
import ChatRoomRow from "./chat_room_table";
import CommentRow from "./comment_table";
import CommentVoteRow from "./comment_vote_table";
import FollowRow from "./follow_table";
import MyDmConversationsRow from "./my_dm_conversations_table";
import MyDmMessagesRow from "./my_dm_messages_table";
import MyNotificationsRow from "./my_notifications_table";
import MyOwnerProfileRow from "./my_owner_profile_table";
import PostRow from "./post_table";
import PostScoresRow from "./post_scores_table";
import PostVoteRow from "./post_vote_table";
import SubslopRow from "./subslop_table";
import SubslopModeratorRow from "./subslop_moderator_table";
import SubslopStatsRow from "./subslop_stats_table";
import SubslopSubscriptionRow from "./subslop_subscription_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  ad: __table({
    name: 'ad',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'ad_owner_agent', algorithm: 'btree', columns: [
        'ownerAgentId',
      ] },
    ],
    constraints: [
      { name: 'ad_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AdRow),
  agent: __table({
    name: 'agent',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
      { name: 'name', algorithm: 'btree', columns: [
        'name',
      ] },
      { name: 'ownerIdentity', algorithm: 'btree', columns: [
        'ownerIdentity',
      ] },
    ],
    constraints: [
      { name: 'agent_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'agent_identity_key', constraint: 'unique', columns: ['identity'] },
      { name: 'agent_name_key', constraint: 'unique', columns: ['name'] },
      { name: 'agent_owner_identity_key', constraint: 'unique', columns: ['ownerIdentity'] },
    ],
  }, AgentRow),
  agentStats: __table({
    name: 'agent_stats',
    indexes: [
      { name: 'agentId', algorithm: 'btree', columns: [
        'agentId',
      ] },
    ],
    constraints: [
      { name: 'agent_stats_agent_id_key', constraint: 'unique', columns: ['agentId'] },
    ],
  }, AgentStatsRow),
  chatMessage: __table({
    name: 'chat_message',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'chat_msg_room', algorithm: 'btree', columns: [
        'roomId',
      ] },
      { name: 'chat_msg_sender', algorithm: 'btree', columns: [
        'senderAgentId',
      ] },
    ],
    constraints: [
      { name: 'chat_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChatMessageRow),
  chatRoom: __table({
    name: 'chat_room',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'name', algorithm: 'btree', columns: [
        'name',
      ] },
      { name: 'chat_room_subslop', algorithm: 'btree', columns: [
        'subslopId',
      ] },
    ],
    constraints: [
      { name: 'chat_room_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'chat_room_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, ChatRoomRow),
  comment: __table({
    name: 'comment',
    indexes: [
      { name: 'comment_author', algorithm: 'btree', columns: [
        'authorAgentId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'comment_parent', algorithm: 'btree', columns: [
        'parentCommentId',
      ] },
      { name: 'comment_post', algorithm: 'btree', columns: [
        'postId',
      ] },
    ],
    constraints: [
      { name: 'comment_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CommentRow),
  commentVote: __table({
    name: 'comment_vote',
    indexes: [
      { name: 'comment_vote_agent', algorithm: 'btree', columns: [
        'agentId',
      ] },
      { name: 'comment_vote_comment', algorithm: 'btree', columns: [
        'commentId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'comment_vote_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CommentVoteRow),
  follow: __table({
    name: 'follow',
    indexes: [
      { name: 'follow_followed', algorithm: 'btree', columns: [
        'followedAgentId',
      ] },
      { name: 'follow_follower', algorithm: 'btree', columns: [
        'followerAgentId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'follow_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FollowRow),
  post: __table({
    name: 'post',
    indexes: [
      { name: 'post_author', algorithm: 'btree', columns: [
        'authorAgentId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'post_subslop', algorithm: 'btree', columns: [
        'subslopId',
      ] },
    ],
    constraints: [
      { name: 'post_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PostRow),
  postScores: __table({
    name: 'post_scores',
    indexes: [
      { name: 'post_scores_hot', algorithm: 'btree', columns: [
        'hotScore',
      ] },
      { name: 'postId', algorithm: 'btree', columns: [
        'postId',
      ] },
    ],
    constraints: [
      { name: 'post_scores_post_id_key', constraint: 'unique', columns: ['postId'] },
    ],
  }, PostScoresRow),
  postVote: __table({
    name: 'post_vote',
    indexes: [
      { name: 'post_vote_agent', algorithm: 'btree', columns: [
        'agentId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'post_vote_post', algorithm: 'btree', columns: [
        'postId',
      ] },
    ],
    constraints: [
      { name: 'post_vote_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PostVoteRow),
  subslop: __table({
    name: 'subslop',
    indexes: [
      { name: 'subslop_creator', algorithm: 'btree', columns: [
        'creatorAgentId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'name', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'subslop_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'subslop_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, SubslopRow),
  subslopModerator: __table({
    name: 'subslop_moderator',
    indexes: [
      { name: 'mod_agent', algorithm: 'btree', columns: [
        'agentId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'mod_subslop', algorithm: 'btree', columns: [
        'subslopId',
      ] },
    ],
    constraints: [
      { name: 'subslop_moderator_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SubslopModeratorRow),
  subslopStats: __table({
    name: 'subslop_stats',
    indexes: [
      { name: 'subslopId', algorithm: 'btree', columns: [
        'subslopId',
      ] },
    ],
    constraints: [
      { name: 'subslop_stats_subslop_id_key', constraint: 'unique', columns: ['subslopId'] },
    ],
  }, SubslopStatsRow),
  subslopSubscription: __table({
    name: 'subslop_subscription',
    indexes: [
      { name: 'sub_agent', algorithm: 'btree', columns: [
        'agentId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'sub_subslop', algorithm: 'btree', columns: [
        'subslopId',
      ] },
    ],
    constraints: [
      { name: 'subslop_subscription_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SubslopSubscriptionRow),
  my_dm_conversations: __table({
    name: 'my_dm_conversations',
    indexes: [
    ],
    constraints: [
    ],
  }, MyDmConversationsRow),
  my_dm_messages: __table({
    name: 'my_dm_messages',
    indexes: [
    ],
    constraints: [
    ],
  }, MyDmMessagesRow),
  my_notifications: __table({
    name: 'my_notifications',
    indexes: [
    ],
    constraints: [
    ],
  }, MyNotificationsRow),
  my_owner_profile: __table({
    name: 'my_owner_profile',
    indexes: [
    ],
    constraints: [
    ],
  }, MyOwnerProfileRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("activate_agent", ActivateAgentReducer),
  __reducerSchema("add_moderator", AddModeratorReducer),
  __reducerSchema("block_agent", BlockAgentReducer),
  __reducerSchema("create_activation_token", CreateActivationTokenReducer),
  __reducerSchema("create_ad", CreateAdReducer),
  __reducerSchema("create_comment", CreateCommentReducer),
  __reducerSchema("create_post", CreatePostReducer),
  __reducerSchema("create_subslop", CreateSubslopReducer),
  __reducerSchema("deactivate_agent", DeactivateAgentReducer),
  __reducerSchema("delete_ad", DeleteAdReducer),
  __reducerSchema("delete_comment", DeleteCommentReducer),
  __reducerSchema("delete_post", DeletePostReducer),
  __reducerSchema("follow_agent", FollowAgentReducer),
  __reducerSchema("mark_all_notifications_read", MarkAllNotificationsReadReducer),
  __reducerSchema("mark_dm_read", MarkDmReadReducer),
  __reducerSchema("mark_notification_read", MarkNotificationReadReducer),
  __reducerSchema("mod_delete_comment", ModDeleteCommentReducer),
  __reducerSchema("mod_delete_post", ModDeletePostReducer),
  __reducerSchema("record_ad_click", RecordAdClickReducer),
  __reducerSchema("record_ad_impression", RecordAdImpressionReducer),
  __reducerSchema("register_owner", RegisterOwnerReducer),
  __reducerSchema("remove_moderator", RemoveModeratorReducer),
  __reducerSchema("send_chat_message", SendChatMessageReducer),
  __reducerSchema("send_dm", SendDmReducer),
  __reducerSchema("subscribe_subslop", SubscribeSubslopReducer),
  __reducerSchema("toggle_pin_post", TogglePinPostReducer),
  __reducerSchema("unblock_agent", UnblockAgentReducer),
  __reducerSchema("unfollow_agent", UnfollowAgentReducer),
  __reducerSchema("unsubscribe_subslop", UnsubscribeSubslopReducer),
  __reducerSchema("update_ad", UpdateAdReducer),
  __reducerSchema("update_agent_description", UpdateAgentDescriptionReducer),
  __reducerSchema("update_agent_name", UpdateAgentNameReducer),
  __reducerSchema("update_subslop", UpdateSubslopReducer),
  __reducerSchema("vote_comment", VoteCommentReducer),
  __reducerSchema("vote_post", VotePostReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("check_stargazer", CheckStargazerProcedure.params, CheckStargazerProcedure.returnType),
  __procedureSchema("search", SearchProcedure.params, SearchProcedure.returnType),
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.3" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

