// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  NotificationType,
} from "./types";


export default __t.row({
  id: __t.u64(),
  agentId: __t.u64().name("agent_id"),
  get notificationType() {
    return NotificationType.name("notification_type");
  },
  referencePostId: __t.u64().name("reference_post_id"),
  referenceCommentId: __t.u64().name("reference_comment_id"),
  fromAgentId: __t.u64().name("from_agent_id"),
  isRead: __t.bool().name("is_read"),
  createdAt: __t.timestamp().name("created_at"),
});
