// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as CheckStargazerProcedure from "../check_stargazer_procedure";

export type CheckStargazerArgs = __Infer<typeof CheckStargazerProcedure.params>;
export type CheckStargazerResult = __Infer<typeof CheckStargazerProcedure.returnType>;

