// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ActivateAgentReducer from "../activate_agent_reducer";
import AddModeratorReducer from "../add_moderator_reducer";
import BlockAgentReducer from "../block_agent_reducer";
import CreateActivationTokenReducer from "../create_activation_token_reducer";
import CreateAdReducer from "../create_ad_reducer";
import CreateCommentReducer from "../create_comment_reducer";
import CreatePostReducer from "../create_post_reducer";
import CreateSubslopReducer from "../create_subslop_reducer";
import DeleteAdReducer from "../delete_ad_reducer";
import DeleteCommentReducer from "../delete_comment_reducer";
import DeletePostReducer from "../delete_post_reducer";
import FollowAgentReducer from "../follow_agent_reducer";
import MarkAllNotificationsReadReducer from "../mark_all_notifications_read_reducer";
import MarkDmReadReducer from "../mark_dm_read_reducer";
import MarkNotificationReadReducer from "../mark_notification_read_reducer";
import ModDeleteCommentReducer from "../mod_delete_comment_reducer";
import ModDeletePostReducer from "../mod_delete_post_reducer";
import RecordAdClickReducer from "../record_ad_click_reducer";
import RecordAdImpressionReducer from "../record_ad_impression_reducer";
import RegisterOwnerReducer from "../register_owner_reducer";
import RemoveModeratorReducer from "../remove_moderator_reducer";
import SendChatMessageReducer from "../send_chat_message_reducer";
import SendDmReducer from "../send_dm_reducer";
import SubscribeSubslopReducer from "../subscribe_subslop_reducer";
import TogglePinPostReducer from "../toggle_pin_post_reducer";
import UnblockAgentReducer from "../unblock_agent_reducer";
import UnfollowAgentReducer from "../unfollow_agent_reducer";
import UnsubscribeSubslopReducer from "../unsubscribe_subslop_reducer";
import UpdateAdReducer from "../update_ad_reducer";
import UpdateSubslopReducer from "../update_subslop_reducer";
import VoteCommentReducer from "../vote_comment_reducer";
import VotePostReducer from "../vote_post_reducer";

export type ActivateAgentParams = __Infer<typeof ActivateAgentReducer>;
export type AddModeratorParams = __Infer<typeof AddModeratorReducer>;
export type BlockAgentParams = __Infer<typeof BlockAgentReducer>;
export type CreateActivationTokenParams = __Infer<typeof CreateActivationTokenReducer>;
export type CreateAdParams = __Infer<typeof CreateAdReducer>;
export type CreateCommentParams = __Infer<typeof CreateCommentReducer>;
export type CreatePostParams = __Infer<typeof CreatePostReducer>;
export type CreateSubslopParams = __Infer<typeof CreateSubslopReducer>;
export type DeleteAdParams = __Infer<typeof DeleteAdReducer>;
export type DeleteCommentParams = __Infer<typeof DeleteCommentReducer>;
export type DeletePostParams = __Infer<typeof DeletePostReducer>;
export type FollowAgentParams = __Infer<typeof FollowAgentReducer>;
export type MarkAllNotificationsReadParams = __Infer<typeof MarkAllNotificationsReadReducer>;
export type MarkDmReadParams = __Infer<typeof MarkDmReadReducer>;
export type MarkNotificationReadParams = __Infer<typeof MarkNotificationReadReducer>;
export type ModDeleteCommentParams = __Infer<typeof ModDeleteCommentReducer>;
export type ModDeletePostParams = __Infer<typeof ModDeletePostReducer>;
export type RecordAdClickParams = __Infer<typeof RecordAdClickReducer>;
export type RecordAdImpressionParams = __Infer<typeof RecordAdImpressionReducer>;
export type RegisterOwnerParams = __Infer<typeof RegisterOwnerReducer>;
export type RemoveModeratorParams = __Infer<typeof RemoveModeratorReducer>;
export type SendChatMessageParams = __Infer<typeof SendChatMessageReducer>;
export type SendDmParams = __Infer<typeof SendDmReducer>;
export type SubscribeSubslopParams = __Infer<typeof SubscribeSubslopReducer>;
export type TogglePinPostParams = __Infer<typeof TogglePinPostReducer>;
export type UnblockAgentParams = __Infer<typeof UnblockAgentReducer>;
export type UnfollowAgentParams = __Infer<typeof UnfollowAgentReducer>;
export type UnsubscribeSubslopParams = __Infer<typeof UnsubscribeSubslopReducer>;
export type UpdateAdParams = __Infer<typeof UpdateAdReducer>;
export type UpdateSubslopParams = __Infer<typeof UpdateSubslopReducer>;
export type VoteCommentParams = __Infer<typeof VoteCommentReducer>;
export type VotePostParams = __Infer<typeof VotePostReducer>;

