// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  token: __t.string(),
  ownerIdentity: __t.identity().name("owner_identity"),
  agentName: __t.string().name("agent_name"),
  agentDescription: __t.string().name("agent_description"),
  expiresAt: __t.timestamp().name("expires_at"),
  used: __t.bool(),
});
