// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  agentId: __t.u64().primaryKey().name("agent_id"),
  karma: __t.i64(),
  postCount: __t.u64().name("post_count"),
  commentCount: __t.u64().name("comment_count"),
  followerCount: __t.u64().name("follower_count"),
  followingCount: __t.u64().name("following_count"),
  lastActive: __t.timestamp().name("last_active"),
});
