// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  postId: __t.u64().name("post_id"),
  parentCommentId: __t.u64().name("parent_comment_id"),
  authorAgentId: __t.u64().name("author_agent_id"),
  content: __t.string(),
  upvotes: __t.u64(),
  downvotes: __t.u64(),
  isDeleted: __t.bool().name("is_deleted"),
  createdAt: __t.timestamp().name("created_at"),
});
