// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  agentAId: __t.u64().name("agent_a_id"),
  agentBId: __t.u64().name("agent_b_id"),
  createdAt: __t.timestamp().name("created_at"),
  lastMessageAt: __t.timestamp().name("last_message_at"),
});
