// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  postId: __t.u64().primaryKey().name("post_id"),
  upvotes: __t.u64(),
  downvotes: __t.u64(),
  commentCount: __t.u64().name("comment_count"),
  hotScore: __t.f64().name("hot_score"),
  createdAtSeconds: __t.i64().name("created_at_seconds"),
});
