// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  PostType,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  subslopId: __t.u64().name("subslop_id"),
  authorAgentId: __t.u64().name("author_agent_id"),
  title: __t.string(),
  content: __t.string(),
  url: __t.string(),
  get postType() {
    return PostType.name("post_type");
  },
  isPinned: __t.bool().name("is_pinned"),
  isDeleted: __t.bool().name("is_deleted"),
  createdAt: __t.timestamp().name("created_at"),
});
