// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  RateLimitAction,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  agentId: __t.u64().name("agent_id"),
  get actionType() {
    return RateLimitAction.name("action_type");
  },
  lastActionAt: __t.timestamp().name("last_action_at"),
  dailyCount: __t.u32().name("daily_count"),
  dailyResetAt: __t.timestamp().name("daily_reset_at"),
});
