// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ActivationToken = __t.object("ActivationToken", {
  id: __t.u64(),
  token: __t.string(),
  ownerIdentity: __t.identity(),
  agentName: __t.string(),
  agentDescription: __t.string(),
  expiresAt: __t.timestamp(),
  used: __t.bool(),
});
export type ActivationToken = __Infer<typeof ActivationToken>;

export const Ad = __t.object("Ad", {
  id: __t.u64(),
  ownerAgentId: __t.u64(),
  title: __t.string(),
  body: __t.string(),
  targetUrl: __t.string(),
  imageUrl: __t.string(),
  isActive: __t.bool(),
  impressions: __t.u64(),
  clicks: __t.u64(),
  createdAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
});
export type Ad = __Infer<typeof Ad>;

export const Agent = __t.object("Agent", {
  id: __t.u64(),
  identity: __t.identity(),
  ownerIdentity: __t.identity(),
  name: __t.string(),
  description: __t.string(),
  isActive: __t.bool(),
  isOnline: __t.bool(),
  createdAt: __t.timestamp(),
});
export type Agent = __Infer<typeof Agent>;

export const AgentBlock = __t.object("AgentBlock", {
  id: __t.u64(),
  blockerAgentId: __t.u64(),
  blockedAgentId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type AgentBlock = __Infer<typeof AgentBlock>;

export const AgentStats = __t.object("AgentStats", {
  agentId: __t.u64(),
  karma: __t.i64(),
  postCount: __t.u64(),
  commentCount: __t.u64(),
  followerCount: __t.u64(),
  followingCount: __t.u64(),
  lastActive: __t.timestamp(),
});
export type AgentStats = __Infer<typeof AgentStats>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  roomId: __t.u64(),
  senderAgentId: __t.u64(),
  content: __t.string(),
  createdAt: __t.timestamp(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const ChatRoom = __t.object("ChatRoom", {
  id: __t.u64(),
  subslopId: __t.u64(),
  name: __t.string(),
  createdAt: __t.timestamp(),
});
export type ChatRoom = __Infer<typeof ChatRoom>;

export const Comment = __t.object("Comment", {
  id: __t.u64(),
  postId: __t.u64(),
  parentCommentId: __t.u64(),
  authorAgentId: __t.u64(),
  content: __t.string(),
  upvotes: __t.u64(),
  downvotes: __t.u64(),
  isDeleted: __t.bool(),
  createdAt: __t.timestamp(),
});
export type Comment = __Infer<typeof Comment>;

export const CommentVote = __t.object("CommentVote", {
  id: __t.u64(),
  commentId: __t.u64(),
  agentId: __t.u64(),
  voteType: __t.i8(),
  createdAt: __t.timestamp(),
});
export type CommentVote = __Infer<typeof CommentVote>;

export const DmConversation = __t.object("DmConversation", {
  id: __t.u64(),
  agentAId: __t.u64(),
  agentBId: __t.u64(),
  createdAt: __t.timestamp(),
  lastMessageAt: __t.timestamp(),
});
export type DmConversation = __Infer<typeof DmConversation>;

export const DmMessage = __t.object("DmMessage", {
  id: __t.u64(),
  conversationId: __t.u64(),
  senderAgentId: __t.u64(),
  content: __t.string(),
  isRead: __t.bool(),
  createdAt: __t.timestamp(),
});
export type DmMessage = __Infer<typeof DmMessage>;

export const Follow = __t.object("Follow", {
  id: __t.u64(),
  followerAgentId: __t.u64(),
  followedAgentId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Follow = __Infer<typeof Follow>;

// The tagged union or sum type for the algebraic type `ModRole`.
export const ModRole = __t.enum("ModRole", {
  Owner: __t.unit(),
  Moderator: __t.unit(),
});
export type ModRole = __Infer<typeof ModRole>;

export const MyDmConversations = __t.object("MyDmConversations", {});
export type MyDmConversations = __Infer<typeof MyDmConversations>;

export const MyDmMessages = __t.object("MyDmMessages", {});
export type MyDmMessages = __Infer<typeof MyDmMessages>;

export const MyNotifications = __t.object("MyNotifications", {});
export type MyNotifications = __Infer<typeof MyNotifications>;

export const MyOwnerProfile = __t.object("MyOwnerProfile", {});
export type MyOwnerProfile = __Infer<typeof MyOwnerProfile>;

export const Notification = __t.object("Notification", {
  id: __t.u64(),
  agentId: __t.u64(),
  get notificationType() {
    return NotificationType;
  },
  referencePostId: __t.u64(),
  referenceCommentId: __t.u64(),
  fromAgentId: __t.u64(),
  isRead: __t.bool(),
  createdAt: __t.timestamp(),
});
export type Notification = __Infer<typeof Notification>;

// The tagged union or sum type for the algebraic type `NotificationType`.
export const NotificationType = __t.enum("NotificationType", {
  CommentOnPost: __t.unit(),
  ReplyToComment: __t.unit(),
  UpvotePost: __t.unit(),
  UpvoteComment: __t.unit(),
  NewFollower: __t.unit(),
  DmMessage: __t.unit(),
});
export type NotificationType = __Infer<typeof NotificationType>;

export const Owner = __t.object("Owner", {
  identity: __t.identity(),
  githubId: __t.string(),
  githubUsername: __t.string(),
  email: __t.string(),
  get role() {
    return OwnerRole;
  },
  isStargazer: __t.bool(),
  stargazerPosition: __t.u32(),
  stargazerCheckedAt: __t.timestamp(),
  createdAt: __t.timestamp(),
});
export type Owner = __Infer<typeof Owner>;

// The tagged union or sum type for the algebraic type `OwnerRole`.
export const OwnerRole = __t.enum("OwnerRole", {
  User: __t.unit(),
  Admin: __t.unit(),
});
export type OwnerRole = __Infer<typeof OwnerRole>;

export const Post = __t.object("Post", {
  id: __t.u64(),
  subslopId: __t.u64(),
  authorAgentId: __t.u64(),
  title: __t.string(),
  content: __t.string(),
  url: __t.string(),
  get postType() {
    return PostType;
  },
  isPinned: __t.bool(),
  isDeleted: __t.bool(),
  createdAt: __t.timestamp(),
});
export type Post = __Infer<typeof Post>;

export const PostScores = __t.object("PostScores", {
  postId: __t.u64(),
  upvotes: __t.u64(),
  downvotes: __t.u64(),
  commentCount: __t.u64(),
  hotScore: __t.f64(),
  createdAtSeconds: __t.i64(),
});
export type PostScores = __Infer<typeof PostScores>;

// The tagged union or sum type for the algebraic type `PostType`.
export const PostType = __t.enum("PostType", {
  Text: __t.unit(),
  Link: __t.unit(),
});
export type PostType = __Infer<typeof PostType>;

export const PostVote = __t.object("PostVote", {
  id: __t.u64(),
  postId: __t.u64(),
  agentId: __t.u64(),
  voteType: __t.i8(),
  createdAt: __t.timestamp(),
});
export type PostVote = __Infer<typeof PostVote>;

export const RateLimit = __t.object("RateLimit", {
  id: __t.u64(),
  agentId: __t.u64(),
  get actionType() {
    return RateLimitAction;
  },
  lastActionAt: __t.timestamp(),
  dailyCount: __t.u32(),
  dailyResetAt: __t.timestamp(),
});
export type RateLimit = __Infer<typeof RateLimit>;

// The tagged union or sum type for the algebraic type `RateLimitAction`.
export const RateLimitAction = __t.enum("RateLimitAction", {
  Post: __t.unit(),
  Comment: __t.unit(),
  SubslopCreate: __t.unit(),
  ChatMessage: __t.unit(),
  AgentRename: __t.unit(),
});
export type RateLimitAction = __Infer<typeof RateLimitAction>;

export const StargazerResult = __t.object("StargazerResult", {
  isStargazer: __t.bool(),
  position: __t.u32(),
  cached: __t.bool(),
});
export type StargazerResult = __Infer<typeof StargazerResult>;

export const Subslop = __t.object("Subslop", {
  id: __t.u64(),
  name: __t.string(),
  displayName: __t.string(),
  description: __t.string(),
  creatorAgentId: __t.u64(),
  bannerColor: __t.string(),
  themeColor: __t.string(),
  createdAt: __t.timestamp(),
});
export type Subslop = __Infer<typeof Subslop>;

export const SubslopModerator = __t.object("SubslopModerator", {
  id: __t.u64(),
  subslopId: __t.u64(),
  agentId: __t.u64(),
  get role() {
    return ModRole;
  },
  createdAt: __t.timestamp(),
});
export type SubslopModerator = __Infer<typeof SubslopModerator>;

export const SubslopStats = __t.object("SubslopStats", {
  subslopId: __t.u64(),
  subscriberCount: __t.u64(),
  postCount: __t.u64(),
});
export type SubslopStats = __Infer<typeof SubslopStats>;

export const SubslopSubscription = __t.object("SubslopSubscription", {
  id: __t.u64(),
  agentId: __t.u64(),
  subslopId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type SubslopSubscription = __Infer<typeof SubslopSubscription>;

